//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HPL.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class PlayerDetail
    {
        public int Id { get; set; }
        [DisplayName("Employee Id")]
        [Required(ErrorMessage = "Employee Id is required")]
        [Range(1, 1000000, ErrorMessage = "Value should be greater than {1}")]
        public int EmployeeId { get; set; }
        [DisplayName("First Name")]
        [Required(ErrorMessage = "First Name is required")]
        public string FirstName { get; set; }
        [DisplayName("Last Name")]
        [Required(ErrorMessage = "Last Name is required")]
        public string LastName { get; set; }
        [DisplayName("About You")]
        [Required(ErrorMessage = "About You is required")]
        public string Description { get; set; }
        [DisplayName("Achievements")]
        public string Achievement { get; set; }
        [DisplayName("Employee Photo")]
        public string ImageUrl { get; set; }
        public HttpPostedFileBase UploadedImage { get; set; }
    }
}
